### ISSUE TITLE
Unit test crashes on Kokkos::LayoutStride::order_dimensions

### ISSUE THREAD

**Issue by mlohry** [kokkos/kokkos#3181]
Starting from a clean build with cmake configuration:
```
-DCMAKE_CXX_COMPILER=g++ -DKokkos_ENABLE_OPENMP=Off -DKokkos_ARCH_HSW=On -DKokkos_ENABLE_HWLOC=On -DKokkos_ENABLE_TESTS=On -DKokkos_ENABLE_SERIAL=On
```

on g++ 9.3.0, ubuntu 20.04, I get an immediate failure in KokkosCore_UnitTest_Serial, gdb trace pasted below. Similar error for OpenMP test.

```
Starting program: /home/mlohry/dev/build-kokkos/core/unit_test/KokkosCore_UnitTest_Serial 
[==========] Running 178 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 2 tests from serial_DeathTest
[ RUN      ] serial_DeathTest.view_layoutstride_right_to_layoutleft_assignment
view_layoutstride_right_to_layoutleft_assignment: srand(1594577725)

Program received signal SIGILL, Illegal instruction.
0x0000555555d522ca in Kokkos::LayoutStride Kokkos::LayoutStride::order_dimensions<int, int>(int, int const*, int const*) ()
(gdb) bt
#0  0x0000555555d522ca in Kokkos::LayoutStride Kokkos::LayoutStride::order_dimensions<int, int>(int, int const*, int const*) ()
#1  0x0000555555e37987 in Test::serial_DeathTest_view_layoutstride_right_to_layoutleft_assignment_Test::TestBody() ()
#2  0x00005555560058fe in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ()
#3  0x0000555556000595 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ()
#4  0x0000555555fe526e in testing::Test::Run() ()
#5  0x0000555555fe5b08 in testing::TestInfo::Run() ()
#6  0x0000555555fe6190 in testing::TestCase::Run() ()
#7  0x0000555555fed281 in testing::internal::UnitTestImpl::RunAllTests() ()
#8  0x0000555556006d9e in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) ()
#9  0x0000555556001651 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) ()
#10 0x0000555555febefa in testing::UnitTest::Run() ()
#11 0x000055555557df5f in RUN_ALL_TESTS() ()
#12 0x000055555557ded7 in main ()
```

**Comment by mlohry** [comment]
Sorry, I had the wrong architecture specified in the cmake config.
