### ISSUE TITLE
Errors in space-time-stack that may come from Kokkos

### ISSUE THREAD

**Issue by DavidPoliakoff** [kokkos/kokkos#3316]
We have users who are running into issues in the space time stack in ways that seem like they may be coming from inside Kokkos, not the tool.

```
                #0  std::_Rb_tree_rebalance_for_erase (__z=0xa02770, __header=...)
                    at ../../../../../gcc-7.3.0/libstdc++-v3/src/c++98/tree.cc:408
                #1  0x00002aaaac59056a in _M_erase_aux (__position=..., this=0xa10d48)
                    at /gpfs/packages/gcc/7.3/include/c++/7.3.0/bits/stl_tree.h:2473
                #2  erase (__position=..., this=0xa10d48) at /gpfs/packages/gcc/7.3/include/c++/7.3.0/bits/stl_tree.h:1113
                #3  erase (__position=..., this=0xa10d48) at /gpfs/packages/gcc/7.3/include/c++/7.3.0/bits/stl_set.h:645
                #4  (anonymous namespace)::Allocations::deallocate(<unknown type in /path/to/kokkos/kokkos-tools/profiling/space-time-stack/kp_space_time_stack.so, CU 0x0, DIE 0x2e89b>, void *, uint64_t, (anonymous namespace)::StackNode *) (this=this@entry=0xa10d40,
                    name=name@entry=<unknown type in /path/to/kokkos/kokkos-tools/profiling/space-time-stack/kp_space_time_stack.so, CU 0x0, DIE 0x2e89b>, ptr=ptr@entry=0xa02c00, size=size@entry=48,
                    frame=frame@entry=0xa05580)
                    at /path/to/kokkos/kokkos-tools/profiling/space-time-stack/kp_space_time_stack.cpp:437
                #5  0x00002aaaac591255 in deallocate (size=48, ptr=0xa02c00, name=0x7fffffffb080 "", space=<optimized out>,
                    this=<optimized out>)
                    at /path/to/kokkos/kokkos-tools/profiling/space-time-stack/kp_space_time_stack.cpp:602
                #6  kokkosp_deallocate_data (handle=..., name=0x7fffffffb080 "", ptr=0xa02c00, size=48)
                    at /path/to/kokkos/kokkos-tools/profiling/space-time-stack/kp_space_time_stack.cpp:686
                #7  0x000000000072bd8b in Kokkos::Impl::SharedAllocationRecord<Kokkos::HostSpace, void>::~SharedAllocationRecord (this=0xa029f0, __in_chrg=<optimized out>)
                    at /path/to/kokkos/core/src/impl/Kokkos_HostSpace.cpp:330
                #8  0x00000000004f6630 in ~SharedAllocationRecord (this=0xa029f0, __in_chrg=<optimized out>)
                    at /path/to/kokkos/core/src/impl/Kokkos_SharedAlloc.hpp:220
                #9  Kokkos::Impl::SharedAllocationRecord<Kokkos::HostSpace, Kokkos::Impl::ViewValueFunctor<Kokkos::OpenMP, unsigned int, true> >::~SharedAllocationRecord (this=0xa029f0, __in_chrg=<optimized out>)
                    at /path/to/kokkos/core/src/impl/Kokkos_SharedAlloc.hpp:220
                #10 0x000000000072f29f in Kokkos::Impl::SharedAllocationRecord<void, void>::decrement (arg_record=0xa029f0)
                    at /path/to/kokkos/core/src/impl/Kokkos_SharedAlloc.cpp:289
                #11 0x00000000004fa6ae in Kokkos::Impl::ParallelFor<Kokkos::Impl::ViewValueFunctor<Kokkos::OpenMP, Kokkos::View<unsigned int*, Kokkos::HostSpace>, false>, Kokkos::RangePolicy<Kokkos::OpenMP>, Kokkos::OpenMP>::execute ()
                    at /path/to/kokkos/core/src/impl/Kokkos_SharedAlloc.hpp:351
                #12 0x00002aaaab564aef in GOMP_parallel (
                    fn=0x4fa620 <_ZNK6Kokkos4Impl11ParallelForINS0_16ViewValueFunctorINS_6OpenMPENS_4ViewIPjJNS_9HostSpaceEEEELb0EEENS_11RangePolicyIJS3_EEES3_E7executeEv._omp_fn.9(void)>, data=0x7fffffffb3a8, num_threads=4, flags=0)
                    at ../../../gcc-7.3.0/libgomp/parallel.c:168
                #13 0x0000000000537e8d in execute (this=0x7fffffffb3b0)
                    at /path/to/kokkos/core/src/OpenMP/Kokkos_OpenMP_Parallel.hpp:121
                #14 Kokkos::Impl::ViewValueFunctor<Kokkos::OpenMP, Kokkos::View<unsigned int*, Kokkos::HostSpace>, false>::execute (this=this@entry=0xa02948, arg=arg@entry=true)
                    at /path/to/kokkos/core/src/impl/Kokkos_ViewMapping.hpp:2783
                #15 0x0000000000537f12 in destroy_shared_allocation (this=0xa02948)
                    at /path/to/kokkos/core/src/impl/Kokkos_ViewMapping.hpp:2797
                #16 Kokkos::Impl::(anonymous namespace)::deallocate<Kokkos::HostSpace, Kokkos::Impl::ViewValueFunctor<Kokkos::OpenMP, Kokkos::View<unsigned int*, Kokkos::HostSpace>, false> > (record_ptr=0xa02920)
                    at /path/to/kokkos/core/src/impl/Kokkos_SharedAlloc.hpp:200
                #17 0x000000000072f29f in Kokkos::Impl::SharedAllocationRecord<void, void>::decrement (arg_record=0xa02920)
                    at /path/to/kokkos/core/src/impl/Kokkos_SharedAlloc.cpp:289
                #18 0x000000000070d305 in ~SharedAllocationTracker (this=0x7fffffffb728, __in_chrg=<optimized out>)
                    at /path/to/kokkos/core/src/impl/Kokkos_SharedAlloc.hpp:351
                #19 ~View (this=0x7fffffffb728, __in_chrg=<optimized out>)
                    at /path/to/kokkos/core/src/Kokkos_View.hpp:1725
```

The parts of the tool in question (space-time-stack as of develop)

```c++
                424   void deallocate(std::string&& name, void* ptr, std::uint64_t size,
                425       StackNode* frame) {
                426     auto key = Allocation(std::move(name), ptr, size, frame);
                427     auto it = alloc_set.find(key);
                428     if (it == alloc_set.end()) {
                429       std::stringstream ss;
                430       ss << "WARNING! allocation(\"" << key.name << "\", " << key.ptr
                431          << ", " << key.size << "), deallocated at \"" << frame->get_full_name() << "\", "
                432          << " was not in the currently allocated set!\n";
                433       auto s = ss.str();
                434       std::cerr << s;
                435     } else {
                436       total_size -= it->size;
                437       alloc_set.erase(it);
                438     }
                439   }
 ```

So we're segfaulting on an erase of an iterator we just verified was valid. @jrmadsen noticed immediately, and I noticed 5 hours later, that we're inside a GOMP parallel region (frame 12), which isn't something the tools are currently engineered to handle, and that region is spawned in Kokkos.

I was hoping to get the expertise of people who know how our View tracking works to figure this out, is that GOMP parallel region dangerous? Any thoughts on how else this could break? My lazy answer is that if OpenMP is enabled to put that erase in a single section, but I don't think tools should be called inside a parallel region in our current model

**Comment by stanmoore1** [comment]
https://github.com/kokkos/kokkos-tools/issues/34#issuecomment-378709168

**Comment by stanmoore1** [comment]
Also see https://github.com/kokkos/kokkos/issues/1530. I had this same issue when using views of views. I ended up having to deallocate the inner view in serial on the host to avoid race conditions in kokkos-tools.

**Comment by DavidPoliakoff** [comment]
@stanmoore1 . Sorry we didn't catch it then, in your shoes I'd be a bit frustrated seeing this issue. Hopefully we'll get it right this time, and thanks for keeping it on our radar

**Comment by stanmoore1** [comment]
@DavidPoliakoff no worries, the answer I got previously was that allocating/deallocating views in parallel is not supported and I've been able to work around that easily enough.

**Comment by jrmadsen** [comment]
I hate to be an enabler of bad practices (since based on the other thread, the usage pattern which leads to this error can add overhead and produce memory leaks) but maybe we should either put in a fix to this in the tool. I'm in favor of something like this:

```cpp
static auto primary_tid = std::this_thread::get_id()

void deallocate(...)
{
  if(std::this_thread::get_id() != primary_tid) {
    // Admonish user about pattern
    return;
  }
  // Rest of existing code...
}
```

**Comment by DavidPoliakoff** [comment]
We're gonna look a little more in-depth about how to make stuff thread-safe, but we might try something like this (or a pragma omp single or some garbage like that) as a stopgap
