### ISSUE TITLE
All tests segfault on Power9 

### ISSUE THREAD

**Issue by janciesko** [kokkos/kokkos#4589]
On Power ISA, commit ff083d4f6e39167a7b3d82860956fac925fa9b30 makes all tests segfault as follows. Is it just me seeing this?
```
./core/unit_test/KokkosCore_UnitTest_Serial1
Program received signal SIGSEGV, Segmentation fault.
0x000020000020b11c in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&) () from /lib64/libstdc++.so.6
Missing separate debuginfos, use: debuginfo-install libgcc-4.8.5-39.el7.ppc64le libstdc++-4.8.5-39.el7.ppc64le
(gdb) where
#0  0x000020000020b11c in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&) () from /lib64/libstdc++.so.6
#1  0x0000000010025d28 in InitArguments (this=0x106f3b08 <Kokkos::Tools::tool_arguments>) at /g/g92/ciesko1/Kokkos/kokkos-2/core/src/impl/Kokkos_Profiling.hpp:63
#2  __static_initialization_and_destruction_0 (__initialize_p=1, __priority=65535) at /g/g92/ciesko1/Kokkos/kokkos-2/core/src/impl/Kokkos_Profiling.cpp:74
#3  _GLOBAL__sub_I__ZN6Kokkos5Tools14tool_argumentsE () at /g/g92/ciesko1/Kokkos/kokkos-2/core/src/impl/Kokkos_Profiling.cpp:1251
#4  0x0000000010561ce4 in __libc_csu_init ()
#5  0x00002000003d528c in generic_start_main (main=0x10015c70 <main(int, char**)>, argc=<optimized out>, argv=0x7fffffffc798, auxvec=0x7fffffffccf0, init=0x10561c50 <__libc_csu_init>, rtld_fini=<optimized out>, stack_end=<optimized out>, fini=<optimized out>)
    at ../csu/libc-start.c:225
#6  0x00002000003d54f4 in __libc_start_main (argc=<optimized out>, argv=<optimized out>, ev=<optimized out>, auxvec=<optimized out>, rtld_fini=<optimized out>, stinfo=<optimized out>, stack_on_entry=<optimized out>) at ../sysdeps/unix/sysv/linux/powerpc/libc-start.c:81
#7  0x0000000000000000 in ?? ()
```

Seems like the expression ordering of this seems off, as the struct inits members based on the static var `unset_string_option` which is defined later thus assigning from unallocated memory. This is a suboptimal solution as it depends on the instantiation order of global or static variables. https://github.com/kokkos/kokkos/blob/ff083d4f6e39167a7b3d82860956fac925fa9b30/core/src/impl/Kokkos_Profiling.cpp#L74-L77

The struct members are declared here: https://github.com/kokkos/kokkos/blob/ff083d4f6e39167a7b3d82860956fac925fa9b30/core/src/impl/Kokkos_Profiling.hpp#L63-L73

Changing the order should fix this.

**Comment by dalg24** [comment]
> Changing the order should fix this.

Please check and open a PR if it does
