### ISSUE TITLE
Nightly Trilinos failure in phalanx unit test (all backends) Phalanx_tViewOfViews_MPI_1: Constructor for Kokkos View mismatched number of arguments

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#5175]
**Describe the bug**
Following merge of #4618 builds of Trilinos (all backends) began failing in the Phalanx_tViewOfViews_MPI_1 unit test:
```
23:35:00 1087/2771 Test #1617: Phalanx_tViewOfViews_MPI_1 ...........................................................................***Failed    2.77 sec
...
23:35:00 4. PhalanxViewOfViews_ViewOfView3_DefaultCtorDtor_UnitTest ... [Passed] (9.1e-06 sec)
23:35:00 Constructor for Kokkos View 'a' has mismatched number of arguments. Number of arguments = 8 but dynamic rank = 1 
23:35:00 
...
```

Were there changes in #4618 that altered View behavior? Adding @rppawlo in case the PR exposed a hidden issue within the Phalanx unit test

**Please also include the following items to support reproducing the bug**

**Reproducer** (weaver testbed rhel7W queue):
```bash
# Repos
git clone -b kokkos-promotion https://github.com/trilinos/Trilinos.git
git clone -b develop kokkos
git clone -b develop kokkos-kernels
# Symbolic link to your kokkos and kokkos-kernels repos in Trilinos source directory for source override
cd Trilinos
ln -s <path-to-your-repo>/kokkos kokkos
ln -s <path-to-your-repo>/kokkos-kernels kokkos-kernels

cd $HOME
mkdir -p build
cd build

# Modules and env
export ATDM_CONFIG_REGISTER_CUSTOM_CONFIG_DIR=$TRILINOS_DIR/cmake/std/atdm/contributed/weaver
source $TRILINOS_DIR/cmake/std/atdm/load-env.sh weaver-cuda-10.1-opt
export ATDM_CONFIG_USE_NINJA=OFF
module list
export OMPI_CXX=<path-to-your-kokkos-repo>/bin/nvcc_wrapper

# Configure
cmake \
 -G"Unix Makefiles" \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DCMAKE_INSTALL_PREFIX=$PWD/install \
 -DCMAKE_CXX_STANDARD="14" \
 -DTrilinos_ENABLE_TESTS=OFF \
 -DTrilinos_ENABLE_ALL_PACKAGES=ON \
 -DTrilinos_ENABLE_Phalanx=ON \
 -DPhalanx_ENABLE_TESTS=ON \
 -DKokkos_SOURCE_DIR_OVERRIDE:STRING=kokkos \
 -DKokkosKernels_SOURCE_DIR_OVERRIDE:STRING=kokkos-kernels \
$TRILINOS_DIR
```

**Comment by rppawlo** [comment]
I don't believe this is an issue with the phalanx test, but maybe @crtrott can correct me. I ran gdb on this. Here's the relevant code:
```
using view = Kokkos::View<double*,DeviceMemorySpace>;
using view_host = view::HostMirror;

class Wrapper {
public:
  view a_;
  view b_;
  KOKKOS_INLINE_FUNCTION
  Wrapper() : a_(nullptr,0),b_(nullptr,0) {}

  Wrapper(const view_host& a, const view_host& b)
    : a_(a.label(),a.layout()),b_(b.label(),b.layout())
  {
    Kokkos::deep_copy(a_,a);
    Kokkos::deep_copy(b_,b);
  }
```
The Wrapper ctor that takes two host mirror views is throwing in the construction of a_ from a This constructor takes the label and the layout from a. They are both rank one views. I think the copy constructor might have an issue or maybe it has changed? Note that we use this construction path for a view-of-views that works without UVM. This is working on both cuda and amd backends.

The stack trace is:
```
5. PhalanxViewOfViews_WrapperExample_UnitTest ... Constructor for Kokkos View 'a' has mismatched number of arguments. Number of arguments = 8 but dynamic rank = 1 

Backtrace:
                        [0xf1fda5]
                        [0xf149ba]
                        [0xf14a3b]
                        [0x4523a4]
                        [0x45d12f]
                        [0x441872]
                        [0xeef5b4]
                        [0xef1789]
                        [0xef5658]
                        [0xef7328]
                        [0x424997]
__libc_start_main [0x7fffe23be555]
                        [0x42f56a]

Program received signal SIGABRT, Aborted.
0x00007fffe23d2387 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install blas-3.4.2-8.el7.x86_64 glibc-2.17-326.el7_9.x86_64 lapack-3.4.2-8.el7.x86_64 libgfortran-4.8.5-44.el7.x86_64 libibverbs-22.4-6.el7_9.x86_64 libnl3-3.2.28-4.el7.x86_64 librdmacm-22.4-6.el7_9.x86_64
(gdb) bt
#0  0x00007fffe23d2387 in raise () from /lib64/libc.so.6
#1  0x00007fffe23d3a78 in abort () from /lib64/libc.so.6
#2  0x0000000000f14a40 in Kokkos::Impl::host_abort (message=<optimized out>)
    at /ascldap/users/rppawlo/tmp/Trilinos/kokkos/core/src/impl/Kokkos_Error.cpp:78
#3  0x00000000004523a4 in abort (message=<optimized out>)
    at /ascldap/users/rppawlo/tmp/Trilinos/kokkos/core/src/impl/Kokkos_Error.hpp:232
#4  Kokkos::Impl::runtime_check_rank (dyn_rank=dyn_rank@entry=1, is_void_spec=is_void_spec@entry=true, i0=i0@entry=20, 
    i1=i1@entry=1, i2=i2@entry=1, i3=i3@entry=1, i4=1, i5=1, i6=1, i7=1, label=...)
    at /ascldap/users/rppawlo/tmp/Trilinos/kokkos/core/src/Kokkos_View.hpp:108
#5  0x000000000045d12f in View<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > (
    check_args=Kokkos::View<double*, Kokkos::CudaSpace>::yes, arg_layout=..., arg_prop=..., this=0x7fffffff8630)
    at /ascldap/users/rppawlo/tmp/Trilinos/kokkos/core/src/Kokkos_View.hpp:1453
#6  View<std::__cxx11::basic_string<char> > (arg_layout=..., arg_label=..., this=0x7fffffff8630)
    at /ascldap/users/rppawlo/tmp/Trilinos/kokkos/core/src/Kokkos_View.hpp:1554
#7  Wrapper::Wrapper (this=0x7fffffff8630, a=..., b=...)
    at /ascldap/users/rppawlo/tmp/Trilinos/packages/phalanx/test/ViewOfViews/tPhalanxViewOfViews.cpp:280
#8  0x0000000000441872 in PhalanxViewOfViews_WrapperExample_UnitTest::runUnitTestImpl (this=<optimized out>, out=..., 
    success=@0x7fffffff8b1f: true)
    at /ascldap/users/rppawlo/tmp/Trilinos/packages/phalanx/test/ViewOfViews/tPhalanxViewOfViews.cpp:317
#9  0x0000000000eef5b4 in Teuchos::UnitTestBase::runUnitTest (this=<optimized out>, out=...)
    at /ascldap/users/rppawlo/tmp/Trilinos/packages/teuchos/core/src/Teuchos_UnitTestBase.cpp:62
#10 0x0000000000ef1789 in Teuchos::UnitTestRepository::runUnitTestImpl (unitTest=..., out=...)
    at /ascldap/users/rppawlo/tmp/Trilinos/packages/teuchos/core/src/Teuchos_UnitTestRepository.cpp:539
#11 0x0000000000ef5658 in Teuchos::UnitTestRepository::runUnitTests (out=...)
    at /ascldap/users/rppawlo/tmp/Trilinos/packages/teuchos/core/src/Teuchos_UnitTestRepository.cpp:317
#12 0x0000000000ef7328 in Teuchos::UnitTestRepository::runUnitTestsFromMain (argc=<optimized out>, argv=<optimized out>)
    at /ascldap/users/rppawlo/tmp/Trilinos/packages/teuchos/core/src/Teuchos_UnitTestRepository.cpp:423
#13 0x0000000000424997 in main (argc=<optimized out>, argv=<optimized out>)
    at /ascldap/users/rppawlo/tmp/Trilinos/packages/phalanx/test/Utilities/Phalanx_UnitTestMain.cpp:19
(gdb)
```

**Comment by crtrott** [comment]
I agree that looks like a bug on our side.
