### ISSUE TITLE
Test Failures on NVIDIA A100 and Volta70 Architectures

### ISSUE THREAD

**Issue by ajpowelsnl** [kokkos/kokkos#6233]
**Describe the bug**
Please provide a concise, clear description of the bug, as well as any available error logs.

For NVIDIA A100, there are two test failures for builds of `develop`:

### First Failing Test (A100):

```
11/38 Test #11: Kokkos_CoreUnitTest_Default .................***Failed  Error regular expression found in output. Regex=[  FAILED  ]  1.50 sec

...

 % ./core/unit_test/Kokkos_CoreUnitTest_Default --gtest_color=yes --gtest_filter=defaultdevicetype.shared_space
Note: Google Test filter = defaultdevicetype.shared_space
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from defaultdevicetype
[ RUN      ] defaultdevicetype.shared_space
Page size as reported by os: 4096 bytes 
Allocating 100 pages of memory in SharedSpace.
Behavior found: 
SharedSpace is as fast as local space on repeated access: 0, we expect true 

Please look at the following timings. The first access in a different ExecutionSpace is not evaluated for the test. As we expect the memory to migrate during the first access it might have a higher cycle count than subsequent accesses, depending on your hardware. If the cycles are more than 1.5 times the cycles for pure local memory access, we assume a page migration happened.

################SHARED SPACE####################
DeviceExecutionSpace timings of run 0:
TimingResult contains 10 results:
Duration of loop 0 is 1006 clock cycles. Migration assumed.
Duration of loop 1 is 844 clock cycles. Migration assumed.
Duration of loop 2 is 321 clock cycles. 
Duration of loop 3 is 320 clock cycles. 
Duration of loop 4 is 321 clock cycles. 
Duration of loop 5 is 319 clock cycles. 
Duration of loop 6 is 826 clock cycles. Migration assumed.
Duration of loop 7 is 320 clock cycles. 
Duration of loop 8 is 320 clock cycles. 
Duration of loop 9 is 322 clock cycles. 
HostExecutionSpace timings of run 0:
TimingResult contains 10 results:
Duration of loop 0 is 31 clock cycles. 
Duration of loop 1 is 25 clock cycles. 
Duration of loop 2 is 25 clock cycles. 
Duration of loop 3 is 24 clock cycles. 
Duration of loop 4 is 24 clock cycles. 
Duration of loop 5 is 24 clock cycles. 
Duration of loop 6 is 25 clock cycles. 
Duration of loop 7 is 25 clock cycles. 
Duration of loop 8 is 25 clock cycles. 
Duration of loop 9 is 25 clock cycles. 
DeviceExecutionSpace timings of run 1:
TimingResult contains 10 results:
Duration of loop 0 is 329561 clock cycles. Migration assumed.
Duration of loop 1 is 321 clock cycles. 
Duration of loop 2 is 320 clock cycles. 
Duration of loop 3 is 321 clock cycles. 
Duration of loop 4 is 320 clock cycles. 
Duration of loop 5 is 838 clock cycles. Migration assumed.
Duration of loop 6 is 816 clock cycles. Migration assumed.
Duration of loop 7 is 321 clock cycles. 
Duration of loop 8 is 319 clock cycles. 
Duration of loop 9 is 321 clock cycles. 
HostExecutionSpace timings of run 1:
TimingResult contains 10 results:
Duration of loop 0 is 29 clock cycles. 
Duration of loop 1 is 24 clock cycles. 
Duration of loop 2 is 24 clock cycles. 
Duration of loop 3 is 24 clock cycles. 
Duration of loop 4 is 25 clock cycles. 
Duration of loop 5 is 25 clock cycles. 
Duration of loop 6 is 24 clock cycles. 
Duration of loop 7 is 24 clock cycles. 
Duration of loop 8 is 25 clock cycles. 
Duration of loop 9 is 24 clock cycles. 
DeviceExecutionSpace timings of run 2:
TimingResult contains 10 results:
Duration of loop 0 is 276514 clock cycles. Migration assumed.
Duration of loop 1 is 845 clock cycles. Migration assumed.
Duration of loop 2 is 320 clock cycles. 
Duration of loop 3 is 321 clock cycles. 
Duration of loop 4 is 321 clock cycles. 
Duration of loop 5 is 320 clock cycles. 
Duration of loop 6 is 320 clock cycles. 
Duration of loop 7 is 310 clock cycles. 
Duration of loop 8 is 309 clock cycles. 
Duration of loop 9 is 309 clock cycles. 
HostExecutionSpace timings of run 2:
TimingResult contains 10 results:
Duration of loop 0 is 28 clock cycles. 
Duration of loop 1 is 25 clock cycles. 
Duration of loop 2 is 24 clock cycles. 
Duration of loop 3 is 24 clock cycles. 
Duration of loop 4 is 25 clock cycles. 
Duration of loop 5 is 25 clock cycles. 
Duration of loop 6 is 24 clock cycles. 
Duration of loop 7 is 24 clock cycles. 
Duration of loop 8 is 24 clock cycles. 
Duration of loop 9 is 24 clock cycles. 
################LOCAL SPACE####################
TimingResult contains 10 results:
Duration of loop 0 is 386 clock cycles. 
Duration of loop 1 is 320 clock cycles. 
Duration of loop 2 is 319 clock cycles. 
Duration of loop 3 is 831 clock cycles. 
Duration of loop 4 is 321 clock cycles. 
Duration of loop 5 is 318 clock cycles. 
Duration of loop 6 is 317 clock cycles. 
Duration of loop 7 is 307 clock cycles. 
Duration of loop 8 is 307 clock cycles. 
Duration of loop 9 is 312 clock cycles. 
TimingResult contains 10 results:
Duration of loop 0 is 25 clock cycles. 
Duration of loop 1 is 25 clock cycles. 
Duration of loop 2 is 25 clock cycles. 
Duration of loop 3 is 25 clock cycles. 
Duration of loop 4 is 25 clock cycles. 
Duration of loop 5 is 25 clock cycles. 
Duration of loop 6 is 27 clock cycles. 
Duration of loop 7 is 25 clock cycles. 
Duration of loop 8 is 24 clock cycles. 
Duration of loop 9 is 24 clock cycles. 
/ascldap/users/ajpowel/kokkos_demo_alice/kokkos/core/unit_test/TestSharedSpace.cpp:216: Failure
Value of: passed
  Actual: false
Expected: true
[  FAILED  ] defaultdevicetype.shared_space (111 ms)
[----------] 1 test from defaultdevicetype (111 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (111 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] defaultdevicetype.shared_space

 1 FAILED TEST
```

### Second Failing Test (A100): 

```
Start 27: Kokkos_CoreUnitTest_DeviceAndThreads
27/38 Test #27: Kokkos_CoreUnitTest_DeviceAndThreads ........***Failed    0.11 sec


    Start 27: Kokkos_CoreUnitTest_DeviceAndThreads

27: Test command: /usr/local/anaconda/3-2020-02/bin/python3.7 "-m" "unittest" "-v" "/ascldap/users/ajpowel/kokkos_demo_alice/kokkos/build_serial_cuda/core/unit_test/TestDeviceAndThreads.py"
27: Test timeout computed to be: 1500
27: /ascldap/users/ajpowel/kokkos_demo_alice/kokkos/build_serial_cuda/core/unit_test/TestDeviceAndThreads (unittest.loader._FailedTest) ... ERROR
27: 
27: ======================================================================
27: ERROR: /ascldap/users/ajpowel/kokkos_demo_alice/kokkos/build_serial_cuda/core/unit_test/TestDeviceAndThreads (unittest.loader._FailedTest)
27: ----------------------------------------------------------------------
27: ImportError: Failed to import test module: /ascldap/users/ajpowel/kokkos_demo_alice/kokkos/build_serial_cuda/core/unit_test/TestDeviceAndThreads
27: Traceback (most recent call last):
27:   File "/usr/local/anaconda/3-2020-02/lib/python3.7/unittest/loader.py", line 154, in loadTestsFromName
27:     module = __import__(module_name)
27: ModuleNotFoundError: No module named '/ascldap/users/ajpowel/kokkos_demo_alice/kokkos/build_serial_cuda/core/unit_test/TestDeviceAndThreads'
27: 
27: 
27: ----------------------------------------------------------------------
27: Ran 1 test in 0.000s
27: 
27: FAILED (errors=1)
27/38 Test #27: Kokkos_CoreUnitTest_DeviceAndThreads ........***Failed    0.09 sec


//Attempting to run only the second failing test:


(base) cee-a100-001 173 % ./core/unit_test/Kokkos_CoreUnitTest_DeviceAndThreads
Usage: <executable> NAME_OF_FLAG

```
## For NVIDIA VOLTA70, there is one test failure for `develop`:

```
[ajpowel@kokkos-dev-2 build_ck_tests]$ ctest --rerun-failed --output-on-failure
Test project /ascldap/users/ajpowel/kokkos/build_ck_tests
    Start 27: Kokkos_CoreUnitTest_DeviceAndThreads
1/1 Test #27: Kokkos_CoreUnitTest_DeviceAndThreads ...***Failed    0.26 sec
/ascldap/users/ajpowel/kokkos/build_ck_tests/core/unit_test/TestDeviceAndThreads (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: /ascldap/users/ajpowel/kokkos/build_ck_tests/core/unit_test/TestDeviceAndThreads (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: /ascldap/users/ajpowel/kokkos/build_ck_tests/core/unit_test/TestDeviceAndThreads
Traceback (most recent call last):
  File "/projects/sems/install/rhel7-x86_64/sems/v2/utility/anaconda3/2020.07/gcc/7.3.0/7t6phgv/lib/python3.8/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
ModuleNotFoundError: No module named '/ascldap/users/ajpowel/kokkos/build_ck_tests/core/unit_test/TestDeviceAndThreads'


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)


0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.27 sec

The following tests FAILED:
	 27 - Kokkos_CoreUnitTest_DeviceAndThreads (Failed)
Errors while running CTest

```

**Please also include the following items to support reproducing the bug**
1. compilers (with versions)

## A100 Compilers:

```
 % module list
Currently Loaded Modulefiles:
  1) cde/v3/gcc/10.3.0          3) cde/v3/cmake/3.23.1        5) cde/v3/anaconda3/2021.05
  2) cde/v3/cuda/11.2.2         4) cde/v3/git/2.35.2

```

## VOLTA70 Compilers:

```
$ module list

Currently Loaded Modules:
  1) anaconda3/2020.07   2) cmake/3.24.3   3) git/2.37.0   4) cuda/12.0   5) gcc/11.1
```

3. Kokkos release or commit used (i.e., the sha1 number)

On `develop` (last commit:  80dd6adad7b9333eadd318dc8f98b27a3fe4d49c)

5. platform and backend

NVIDIA / CUDA

7. cmake configure command

## For A100:

```
cmake \
-DKokkos_ARCH_AMPERE80=ON \
-DKokkos_ENABLE_TESTS=ON \
-DKokkos_ENABLE_SERIAL=ON \
-DKokkos_ENABLE_CUDA=ON \
-DCMAKE_CXX_STANDARD=17 \
-DCMAKE_INSTALL_PREFIX=$HOME/kokkos_install_demo_a100 \
-DCMAKE_BUILD_TYPE=Release ..
```

## For Volta70:

```
cmake \
-DKokkos_ENABLE_TESTS=ON \
-DKokkos_ENABLE_CUDA=ON \
-DKokkos_ARCH_VOLTA70=ON \
-DKokkos_ENABLE_SERIAL=ON \
-DCMAKE_CXX_STANDARD=17 \
-DCMAKE_INSTALL_PREFIX=$HOME/kokkos_install_xxx \
-DCMAKE_BUILD_TYPE=Release ..
```

8. output from cmake command

## A100:

```
base) cee-a100-001 179 % ../do_kokkos_cmake_ampere80.sh 
-- Setting default Kokkos CXX standard to 17
-- Kokkos version: 4.1.99
-- The project name is: Kokkos
-- Using internal gtest for testing
-- Compiler Version: 11.2.152
-- kokkos_launch_compiler (/ascldap/users/ajpowel/kokkos_demo_alice/kokkos/bin/kokkos_launch_compiler) is enabled...
-- Using -std=c++17 for C++17 standard as feature
-- Built-in Execution Spaces:
--     Device Parallel: Kokkos::Cuda
--     Host Parallel: NoTypeDefined
--       Host Serial: SERIAL
-- 
-- Architectures:
--  AMPERE80
-- Using internal desul_atomics copy
-- Sources TestCuda.cpp
-- Kokkos Devices: CUDA;SERIAL, Kokkos Backends: CUDA;SERIAL
-- Configuring done
-- Generating done
-- Build files have been written to: /ascldap/users/ajpowel/kokkos_demo_alice/kokkos/build_serial_cuda
(base) cee-a100-001 180 % 
```

## VOLTA70:

```
../do_cmake
-- Setting default Kokkos CXX standard to 17
-- Kokkos version: 4.1.99
-- The project name is: Kokkos
-- Using internal gtest for testing
-- Compiler Version: 12.0.76
-- kokkos_launch_compiler (/ascldap/users/ajpowel/kokkos/bin/kokkos_launch_compiler) is enabled...
-- Using -std=c++17 for C++17 standard as feature
-- Built-in Execution Spaces:
--     Device Parallel: Kokkos::Cuda
--     Host Parallel: NoTypeDefined
--       Host Serial: SERIAL
-- 
-- Architectures:
--  VOLTA70
-- Using internal desul_atomics copy
-- Sources TestCuda.cpp
-- Kokkos Devices: CUDA;SERIAL, Kokkos Backends: CUDA;SERIAL
-- Configuring done
-- Generating done
-- Build files have been written to: /ascldap/users/ajpowel/kokkos/build_ck_tests
```

10. code needed to reproduce the bug

N/A -- Simply running tests.  See information in step 12 below.

12. command line needed to reproduce the bug

In build directory, simply run, `ctest`.

7. please also attach the `KokkosCore_config.h` header file (generated during the build);

Generated header attached

**Any additional info**
Please provide any additional context about the issue here.

**Comment by ajpowelsnl** [comment]
[KokkosCore_config.h.txt](https://github.com/kokkos/kokkos/files/11826449/KokkosCore_config.h.txt)

**Comment by dalg24** [comment]
Why do you have an `anaconda` environment loaded?  Do you have another python you can try on that system.  Presumably you can reproduce that `Kokkos_CoreUnitTest_DeviceAndThreads` failure without CUDA.  The issue is likely something not quite right with you Python environment.

Haven't looked at the page migration issue.

**Comment by ajpowelsnl** [comment]
@dalg24 -- the `Kokkos_CoreUnitTest_DeviceAndThreads` failure occurs with or without the anaconda module loaded. I tried different Python versions (system & anaconda module) to deal with 

```
...
ImportError: Failed to import test module: /ascldap/users/ajpowel/kokkos/build_ck_tests/core/unit_test/TestDeviceAndThreads
...
```

**Comment by dalg24** [comment]
Did you reconfigure in between ?

**Comment by ajpowelsnl** [comment]
I used the system Python initially, then anaconda (via module), but I am checking again now without anaconda.

**Comment by ajpowelsnl** [comment]
This issue is known, and the ` 27 - Kokkos_CoreUnitTest_DeviceAndThreads` should be re-factored for portability / robustness, such that failures are informative for the platform and backend.

**Comment by crtrott** [comment]
There is no refactor required, this is a system issue having an incompatible python or something like that. It is not possible for us to diagnose that.
