### ISSUE TITLE
Integration: Test Failures in Trilinos after Updating

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos#746]
Looks like there are test failures in intrepid2 on White with a CUDA/Serial build:
```
Intrepid2_refactor_unit-test_Discretization_FunctionSpaceTools_Cuda_Test_01_MPI_1
Intrepid2_refactor_unit-test_Discretization_FunctionSpaceTools_Cuda_Test_02_MPI_1
Intrepid2_refactor_unit-test_Discretization_FunctionSpaceTools_Cuda_Test_03_MPI_1
```

There are also more panzer tests failing but, those may just be derivatives of the intrepid issue.

**Comment by crtrott** [comment]
Another test failing on White with OpenMP:
```
Ifpack2_Jacobi_hb_belos_MPI_1
```

**Comment by ndellingwood** [comment]
I did a quick Cuda build with Kokkos develop branch and saw run time errors "Tile dimensions exceed Cuda limits
 Cuda ExecSpace Error: MDRange tile dims exceed maximum number of threads per block - choose smaller tile dims"

@crtrott Are these the same errors you are seeing? If so, the tile dims in the Intrepid2 tests may need to be adjusted when compiling for Cuda

**Comment by ndellingwood** [comment]
Checked requested tile sizes for ./Intrepid2_refactor_unit-test_Discretization_FunctionSpaceTools_Cuda_Test_01.exe

"MDRange runtime check: max product tile size (cuda) = 1024  requested = 74598144  tile0 = 16  tile1 = 4662384  tile2 = 1"

**Comment by ndellingwood** [comment]
For reference:
```
(cuda-gdb) bt
#0  0x0000003862432635 in raise () from /lib64/libc.so.6
#1  0x0000003862433e15 in abort () from /lib64/libc.so.6
#2  0x000000000049da31 in Kokkos::Impl::host_abort (message=0x4b4498 <_IO_stdin_used+25624> " Cuda ExecSpace Error: MDRange tile dims exceed maximum number of threads per block - choose smaller tile dims")
    at /home/ndellin/trilinos/Trilinos/packages/kokkos/core/src/impl/Kokkos_Error.cpp:64
#3  0x00000000004693a0 in Intrepid2::CellTools<Kokkos::Cuda>::setJacobian<double, Kokkos::Cuda, double, Kokkos::Cuda, double, Kokkos::Cuda, Teuchos::RCP<Intrepid2::Basis<Kokkos::Cuda, double, double> > >(Kokkos::Experimental::DynRankView<double<Kokkos::Cuda> >, Kokkos::Experimental::DynRankView<double<Kokkos::Cuda> >, Kokkos::Experimental::DynRankView<double<Kokkos::Cuda> >, Teuchos::RCP<Intrepid2::Basis<Kokkos::Cuda, double, double> >) (jacobian=..., points=..., worksetCell=..., basis=...) at /home/ndellin/trilinos/Trilinos/packages/intrepid2/refactor/src/Cell/Intrepid2_CellToolsDefJacobian.hpp:171
#4  0x0000000000469896 in Intrepid2::CellTools<Kokkos::Cuda>::setJacobian<double, Kokkos::Cuda, double, Kokkos::Cuda, double, Kokkos::Cuda>(Kokkos::Experimental::DynRankView<double<Kokkos::Cuda> >, Kokkos::Experimental::DynRankView<double<Kokkos::Cuda> >, Kokkos::Experimental::DynRankView<double<Kokkos::Cuda> >, shards::CellTopology) (jacobian=..., points=..., worksetCell=..., cellTopo=...)
    at /home/ndellin/trilinos/Trilinos/packages/intrepid2/refactor/src/Cell/Intrepid2_CellTools.hpp:439
#5  0x000000000046cf46 in Intrepid2::Test::FunctionSpaceTools_Test01<double, Kokkos::Cuda> (verbose=false)
    at /home/ndellin/trilinos/Trilinos/packages/intrepid2/refactor/unit-test/Discretization/FunctionSpaceTools/test_01.hpp:211
#6  0x0000000000457a44 in main (argc=1, argv=<optimized out>) at /home/ndellin/trilinos/Trilinos/packages/intrepid2/refactor/unit-test/Discretization/FunctionSpaceTools/Cuda/test_01.cpp:57
```

**Comment by ndellingwood** [comment]
It looks like in Intrepid2 the tile size is not being set, so this is may be due to the change I added in #743 
Will work on and test a fix.

**Comment by crtrott** [comment]
We have a fix. I'll push it in a couple minutes.

**Comment by ndellingwood** [comment]
Beat me to it
