### ISSUE TITLE
Conflict in Integration of Kokkos, PyTorch and PyBind11

### ISSUE THREAD

**Issue by zishengye** [kokkos/kokkos#7603]
**Describe the bug**

When ingrating Kokkos, PyTorch and PyBind11 together, one can't import torch and exported lib, which uses Torch and Kokkos, from PyBind11 in Python at the same time.

**Reproduction of the bug**

Here is a minimal [repo](https://github.com/Pan-Group-UW-Madison/hignn-minimal.git) which can repoduce the error. To launch the example, one may need the [container image](https://registry.hub.docker.com/r/zishengy/hignn) with the command
```
docker run --privileged -it --rm -v $PWD:/local -w /local --entrypoint /bin/bash --gpus=all --shm-size=4g --hostname hignn zishengy/hignn
```
To compile the project, one can use
```
python3 init.py
```

For the details of the docker image, one can find it [here](https://github.com/Pan-Group-UW-Madison/hignn/blob/main/script/Dockerfile.hignn.Amprere). The compiling command is:
```
ENV OMPI_CXX=/opt/kokkos/bin/nvcc_wrapper
RUN cd /opt/ && \
    git clone https://github.com/kokkos/kokkos.git kokkos-source && \
    cd kokkos-source && \
    git checkout release-candidate-4.2.01 && \
    mkdir build && \
    cd build && \
    cmake -D CMAKE_INSTALL_PREFIX=/opt/kokkos -D Kokkos_ENABLE_CUDA=On -D Kokkos_CUDA_DIR=/usr/local/cuda -D Kokkos_ARCH_AMPERE86=On -D Kokkos_ENABLE_OPENMP=On -D CMAKE_CXX_STANDARD=17 -D BUILD_SHARED_LIBS=On .. && \
    make -j$(nproc) && \
    make install && \
    cd /opt/ && \
    rm -rf kokkos-source
```

**Error Output**

When import torch before the exported lib, one can get the error:
```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
```
If the order the flipped, one can get an error:
```
Traceback (most recent call last):
  File "/local/example.py", line 2, in <module>
    import torch
  File "/usr/local/lib/python3.9/dist-packages/torch/__init__.py", line 237, in <module>
    from torch._C import *  # noqa: F403
ImportError: /usr/local/lib/python3.9/dist-packages/torch/lib/libtorch_python.so: undefined symbol: _ZNK5torch3jit5Graph8toStringEb
```

**Comment by masterleinad** [comment]
Can you try with a more recent release or `develop`?

**Comment by masterleinad** [comment]
> Is `release-candidate-4.5.00` to be good? I have tried it but still failed. The docker image with Kokkos 4.5 is [here](https://hub.docker.com/layers/zishengy/hignn/kokkos-4.5/images/sha256-fc7c22b2856e7aed1b681e25fe847ca60c1dc6b65e93fcf00920fedd725df5f3?context=repo).

Yes, that's good.

**Comment by dalg24** [comment]
Why are you checking out release candidate branches instead of actually tagged releases?

**Comment by zishengye** [comment]
I only checked the branches. Anyway, I've tried the tag 4.5.00 as well. It also can't work.

**Comment by dalg24** [comment]
Please confirm whether you check that simple example Kokkos programs such as [Hello World](https://github.com/kokkos/kokkos/blob/c266584530c2dc536f68e6916b2cf1af6aedf2ad/example/tutorial/01_hello_world_lambda/hello_world_lambda.cpp#L32-L79) run without errors on your system.
You could also enable examples and tests (via `-DKokkos_ENABLE_EXAMPLES=ON -DKokkos_ENABLE_TESTS=ON`) and run them with CTest.

**Comment by zishengye** [comment]
I've confirmed that my system can successfully run the Hello World program.

**Comment by JBludau** [comment]
The only thing that comes to my mind is that the runtime might require the libs to be compiled with position independent code

**Comment by zishengye** [comment]
You mean the exported lib or Kokkos itself. If it is the exported lib, I have set it in CMake as [here](https://github.com/Pan-Group-UW-Madison/hignn-minimal/blob/fca90ec9d35f713e96b4caac1ad29518d86d4f09/CMakeLists.txt#L31). If it is Kokkos, I tried the following command and recompiled the lib:
```
cmake -D CMAKE_INSTALL_PREFIX=/opt/kokkos -D Kokkos_ENABLE_CUDA=On -D Kokkos_CUDA_DIR=/usr/local/cuda -D Kokkos_ARCH_AMPERE86=On -D Kokkos_ENABLE_OPENMP=On -D CMAKE_CXX_STANDARD=17 -D BUILD_SHARED_LIBS=On -D CMAKE_POSITION_INDEPENDENT_CODE=On .. && \
```
But, it still can't solve the issue.
